### ISSUE TITLE
Fix composer.json to point-release only versions of associated modules

### ISSUE THREAD

**Issue by nyeholt** [silverstripe-australia/silverstripe-ba-sis#3]

**Comment by nglasl** [comment]
This is to use the ~X.X.X syntax.

**Comment by nglasl** [comment]
Do you still see this being a requirement? Everything is pretty much locked down using ~X.X right now, which I think is better since it picks up when a module introduces a new feature (without breaking anything). ~X.X.X also requires a lot more maintenance.

**Comment by alexclifford** [comment]
Isn't ~X.X.X safer in case someone inadvertently runs composer update without any arguments?

**Comment by nglasl** [comment]
Yes, but is that enough reason to use ~X.X.X, because someone isn't using composer correctly? The problem I have with using ~X.X.X is that whenever a module introduces a new feature, and someone wants to use it, well that's too bad. Ba-sis says you're not allowed to use it.

**Comment by nyeholt** [comment]
That's a git-revert on anything they commit to the project though - and doesn't prevent the project itself from using x.x.x syntax. 

The issue is that if we lock tighter than we are, any minor version increment to a dependent module requires version updates to this module, then an update to the parent project's composer. across multiple modules, which could then trigger updates to _other_ dependent modules. By having it at ~x.x you're able to update the module in the context of the project itself independently of Basis.

**Comment by nglasl** [comment]
@nyeholt, can you please confirm whether we're okay to close the issue?
