### ISSUE TITLE
https://github.com/studiobonito/silverstripe-spamprotection-honeypot

### ISSUE THREAD

**Issue by nglasl** [silverstripe-australia/silverstripe-ba-sis#31]
https://github.com/studiobonito/silverstripe-spamprotection-honeypot/blob/master/composer.json#L26

This module needs to support 3.5.

**Comment by silbinarywolf** [comment]
@nglasl Whats wrong with this PR?
https://github.com/studiobonito/silverstripe-spamprotection-honeypot/pull/8/files

**Comment by silbinarywolf** [comment]
Actually just noticed, probably not ideal if it ends up pulling into a SS4 project.
Will fiddle.

**Comment by nglasl** [comment]
Nothing, and it shouldn't cause it to pull down into a 4.0 project. This is more..

a) Why was this locked down to `<3.3` to begin with? Perhaps there's something nasty in here that doesn't play with 3.5? Perhaps this was just how the dependency was done at the time, just because?
b) This is pretty much an issue so long as that PR hasn't been merged.

**Comment by silbinarywolf** [comment]
Works as expected in 3.5.3.

**Comment by nglasl** [comment]
Closing this issue, since the PR has now been merged, and https://github.com/silverstripe-australia/silverstripe-ba-sis/commit/21b705c32c6f5073bf48d74957ce6312b8bd3744 introduces the support for 3.5.
