### ISSUE TITLE
Error when creating new LinksBlock

### ISSUE THREAD

**Issue by tardinha** [silverstripe-australia/silverstripe-ba-sis#5]
Hey,

When creating a new LinksBlock, the following error occurs.
[User Error] Uncaught InvalidArgumentException: Invalid sort() column

Commenting out [line 28 of LinksBlock.php](https://github.com/silverstripe-australia/silverstripe-ba-sis/blob/master/code/dataobjects/LinksBlock.php#L28) solves the issue.

Cheers

Mark

**Comment by silbinarywolf** [comment]
Has since been resolved.
